server:
  port: 8888
 
spring:
  application:    
    name: properties
  cloud:    
    config:      
      server:        git:          uri: https://github.com/CGonzalez97/Config-Server.git
          default-label: main
          search-paths: '*service'